# Generated by Django 5.0.1 on 2024-02-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(blank=True, max_length=30)),
                ('sex', models.CharField(blank=True, max_length=15)),
                ('nationality', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('l_g_a', models.CharField(max_length=50)),
                ('tribe', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=10)),
                ('guidance_name', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('clas', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('admission_number', models.CharField(max_length=500)),
            ],
        ),
    ]
