# Generated by Django 5.0.1 on 2024-02-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=30),
        ),
    ]
