# Generated by Django 5.0.1 on 2024-02-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_record_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='first_name',
            new_name='s_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='last_name',
        ),
    ]
