# Generated by Django 5.0.1 on 2024-02-12 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_rename_first_name_record_s_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='address',
            new_name='guidance_address',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='occupation',
            new_name='guidance_occupation',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='phone',
            new_name='guidance_phone',
        ),
    ]
